<a href="https://colab.research.google.com/github/Shaikmd3797/numpy-questions-and-answers/blob/main/Numpy_tasks_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [68]:
"The version of numpy is : " ,np.__version__

('The version of numpy is : ', '1.21.6')

In [69]:
np.show_config

<function numpy.__config__.show()>

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [70]:
"The array of null vectors of size 10  :" ,np.zeros(10)

('The array of null vectors of size 10  :',
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [71]:
a=np.zeros((5,5))
"memory size of total array is ",a.size*a.itemsize

('memory size of total array is ', 200)

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [72]:
 np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [73]:
arr=np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [74]:
arr=np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [75]:
arr=np.arange(1,20)
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [76]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [77]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [78]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [79]:
np.random.random((3,3,3))

array([[[0.31021503, 0.76764957, 0.55000591],
        [0.13315631, 0.97103652, 0.01625555],
        [0.99410697, 0.42552763, 0.730425  ]],

       [[0.66644012, 0.27721317, 0.29476332],
        [0.45346265, 0.62365472, 0.17441469],
        [0.01664533, 0.18382487, 0.59621764]],

       [[0.41257954, 0.50691786, 0.72583938],
        [0.90769918, 0.7358881 , 0.74958611],
        [0.8659317 , 0.50967755, 0.841024  ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [80]:
arr=np.random.random((10,10))
arr_min,arr_max=arr.min(),arr.max()
"minumum of array is ",arr_min

('minumum of array is ', 0.0009101076776354411)

In [81]:
"maximum of array is ",arr_max

('maximum of array is ', 0.9957656417835338)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [82]:
A=np.random.random(30)
B=A.mean()
"The mean of array is ",B

('The mean of array is ', 0.5566880096208436)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [83]:
One_D=np.ones((5,5))
One_D[1:-1,1:-1]=0
One_D

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [84]:
A=np.arange(1,10).reshape(3,3)
A=np.pad(A,pad_width=1,mode='constant',constant_values=0)
A

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 7, 8, 9, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [85]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
0.3==3*0.1

nan
False
False
nan


False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [86]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [87]:
X=np.zeros((8,8),dtype=int)
X[1::2,::2]=1
X[::2,1::2]=1
X

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [88]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [89]:
a=np.tile(np.array([[0,10],[10,0]]),(4,4))
a

array([[ 0, 10,  0, 10,  0, 10,  0, 10],
       [10,  0, 10,  0, 10,  0, 10,  0],
       [ 0, 10,  0, 10,  0, 10,  0, 10],
       [10,  0, 10,  0, 10,  0, 10,  0],
       [ 0, 10,  0, 10,  0, 10,  0, 10],
       [10,  0, 10,  0, 10,  0, 10,  0],
       [ 0, 10,  0, 10,  0, 10,  0, 10],
       [10,  0, 10,  0, 10,  0, 10,  0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [90]:
arr=np.random.random((5,5))
nor=(arr-np.min(arr))/(np.max(arr)-np.min(arr))
nor

array([[0.15785035, 0.17838749, 0.45826984, 0.88157973, 0.41211268],
       [0.68066864, 0.51358789, 0.13588604, 0.62989138, 0.02870388],
       [0.15780064, 0.13953165, 0.68097486, 0.25920584, 0.        ],
       [0.31669713, 0.618445  , 0.02953302, 1.        , 0.81990442],
       [0.88677208, 0.8512623 , 0.9829818 , 0.22566774, 0.18439704]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [91]:
color=np.dtype([("R",np.ubyte,1),("G",np.ubyte,1),("B",np.ubyte,1),("A",np.ubyte,1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [92]:
product=np.dot(np.ones((5,3)),np.ones((3,2)))
product

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [93]:
arr=np.arange(11)
arr[(arr>3)&(arr<=8)]*=-1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [94]:
# Author: Jake vanderPlas
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [98]:
2<<arr>>2
arr<-arr
1j*arr
arr/1/1
arr<arr>arr
arr**arr

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [99]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [100]:
arr=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(arr)),arr))

[ -4.   7. -10.   1.  -4.   7.  -2.  -4.  10.   3.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [101]:
arr1=np.random.randint(0,8,8)
arr2=np.random.randint(0,7,7)
np.intersect1d(arr1,arr2)

array([0, 2, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [105]:
ignore=np.seterr(all="ignore")
arr=np.ones(1)/0
with np.errstate(all="ignore"):np.arange(3)/0



#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [103]:
np.sqrt(-1)==np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [106]:
yesterday=np.datetime64('today')-np.timedelta64(1)
today=np.datetime64('today')
tomorrow= np.datetime64('today')+np.timedelta64(1)
print(yesterday,today,tomorrow)


2022-11-28 2022-11-29 2022-11-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [107]:
date=np.arange('2016-07','2016-08',dtype='datetime64[D]')
date

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [108]:
A=np.ones(4)*1
B=np.ones(4)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [109]:
arr=np.random.uniform(0,10,10)
print(arr-arr%1)
print(arr//1)
print(np.floor(arr))
print(arr.astype(int))
print(np.trunc(arr))

[8. 1. 4. 1. 2. 2. 8. 3. 8. 7.]
[8. 1. 4. 1. 2. 2. 8. 3. 8. 7.]
[8. 1. 4. 1. 2. 2. 8. 3. 8. 7.]
[8 1 4 1 2 2 8 3 8 7]
[8. 1. 4. 1. 2. 2. 8. 3. 8. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [110]:
arr=np.tile(np.arange(0,5),(5,1))
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [111]:
def generator():
  for i in range(10):
    yield i
arr=np.fromiter(generator(),dtype=float,count=-1)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [112]:
arr=np.linspace(0.1,1,10,endpoint=False)
arr

array([0.1 , 0.19, 0.28, 0.37, 0.46, 0.55, 0.64, 0.73, 0.82, 0.91])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [113]:
arr=np.random.randint(0,1,10)
arr.sort()
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [114]:
arr=np.arange(15)
np.add.reduce(arr)

105

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [115]:
A=np.random.randint(0,2,10)
B=np.random.randint(0,2,10)
print(np.allclose(A,B))
print(np.array_equal(A,B))

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [116]:
arr=np.ones(10)
arr.flags.writeable=False
arr[1]=3
arr

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [117]:
arr=np.random.random((10,2))
a,b=arr[:,0],arr[:,1]
r=np.sqrt(a*a+b*b)
t=np.arctan2(b,a)
print(r)
print(t)

[0.82280268 0.42270753 0.58963412 0.8868455  0.95034586 0.36294145
 0.69642563 0.56598864 0.73522382 1.25709806]
[0.05844124 1.15129611 1.06153863 1.51285182 0.61331709 0.72495876
 1.43527001 0.10565405 0.76102806 0.82325514]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [118]:
arr=np.random.random(10)
arr[arr.argmax()]=0
arr

array([0.46955664, 0.67324839, 0.3356703 , 0.36434537, 0.68380179,
       0.66008388, 0.0243612 , 0.78025931, 0.12115207, 0.        ])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [119]:
arr=np.zeros((5,5),[('x',int),('y',float)])
arr['x'],arr['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
arr

array([[(0, 0.  ), (0, 0.  ), (0, 0.  ), (0, 0.  ), (1, 0.  )],
       [(0, 0.25), (0, 0.25), (0, 0.25), (0, 0.25), (1, 0.25)],
       [(0, 0.5 ), (0, 0.5 ), (0, 0.5 ), (0, 0.5 ), (1, 0.5 )],
       [(0, 0.75), (0, 0.75), (0, 0.75), (0, 0.75), (1, 0.75)],
       [(0, 1.  ), (0, 1.  ), (0, 1.  ), (0, 1.  ), (1, 1.  )]],
      dtype=[('x', '<i8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [120]:
x=np.random.random(8)
y=np.random.random(8)
C=1/np.subtract.outer(x,y)
print(C)

[[   3.29596322    2.69934823    4.02537483    1.94182219    3.05670584
     1.07602115    2.30837739    2.25006146]
 [  -3.05286092   -3.83872381   -2.61411275   -8.62196584   -3.29149328
     3.35135552   -5.05667747   -5.36104674]
 [  -2.28415515   -2.69730607   -2.02931959   -4.42047829   -2.4151643
     5.31491705   -3.2468023    -3.36963813]
 [   3.70656735    2.96868257    4.65518946    2.07740335    3.40669623
     1.11639573    2.50253578    2.43414268]
 [  -1.63029928   -1.8304091    -1.49619588   -2.48876606   -1.69596104
    79.59240959   -2.06790579   -2.11705874]
 [  -1.70662584   -1.92717899   -1.56023549   -2.67113458   -1.7787157
    25.00199691   -2.19226981   -2.24759175]
 [   3.36501838    2.74549117    4.12885626    1.96558665    3.11600912
     1.08327865    2.3420384     2.28203144]
 [  -4.59271922   -6.63668752   -3.66685445 -162.41240152   -5.15496317
     2.44970516  -11.37234046  -13.03694751]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [121]:
int_dtype=[np.int8,np.int32,np.int64]
float_dtype=[np.float32,np.float64]
for i in int_dtype:
  print(np.iinfo(i).min)
  print(np.iinfo(i).max)
for j in float_dtype:
  print(np.finfo(j).min)
  print(np.finfo(j).max)
  print(np.finfo(j).eps)
  
  

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [122]:
arr=np.ones(10)
np.set_printoptions()
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [123]:
arr=np.arange(50)
v=np.random.uniform(0,50)
i=(np.abs(arr-v)).argmin()
arr[i]

7

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [124]:
arr=np.ones(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
arr

/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py:204: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = empty(shape, dtype, order)


array([((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [125]:
arr=np.random.random((100,2))
A,B=np.atleast_2d(arr[:,0],arr[:,1])
dist=np.sqrt((A-A.T)**2 + (B-B.T)**2)
dist

array([[0.        , 0.20941663, 0.66267667, ..., 0.42394205, 0.72875557,
        0.43564096],
       [0.20941663, 0.        , 0.76913865, ..., 0.61303166, 0.86069651,
        0.64451025],
       [0.66267667, 0.76913865, 0.        , ..., 0.83463828, 0.13677396,
        0.59768947],
       ...,
       [0.42394205, 0.61303166, 0.83463828, ..., 0.        , 0.83065468,
        0.26603623],
       [0.72875557, 0.86069651, 0.13677396, ..., 0.83065468, 0.        ,
        0.57474749],
       [0.43564096, 0.64451025, 0.59768947, ..., 0.26603623, 0.57474749,
        0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [126]:
arr=np.arange(10,dtype=np.float32)
arr=arr.astype(np.int32,copy=False)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [127]:
from io import StringIO
s=StringIO("""1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11""")
arr=np.genfromtxt(s,delimiter=",",dtype=np.int)
arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [128]:
arr=np.arange(9).reshape(3,3)
for i,j in np.ndenumerate(arr):
  print(i,j)
#for k in np.ndindex(arr.shape):
  #(k,arr[k])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [131]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)


[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [130]:
arr=np.zeros((5,10))
np.put(arr, np.random.choice(range(5*10),7),1)
arr

array([[0., 0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [134]:
arr=np.random.random((5,5))
new_arr=arr-arr.mean(axis=1,keepdims=True)
new_arr

array([[ 0.01174338,  0.06458511, -0.09156277,  0.03128299, -0.01604871],
       [ 0.50918647, -0.02860999, -0.12482354, -0.0646235 , -0.29112944],
       [-0.01217662, -0.07784582, -0.02089061,  0.1998069 , -0.08889385],
       [ 0.18751245, -0.30418393, -0.18267603, -0.03140456,  0.33075207],
       [ 0.17642037,  0.06896044, -0.114049  ,  0.3447232 , -0.47605501]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [135]:
arr=np.random.randint(0,16,(4,4))
print(arr)
new_arr=arr[arr[:,2].argsort()]
new_arr

[[ 2 10  1 15]
 [ 1  7  2 13]
 [ 4  1  9 14]
 [ 4 13  7  1]]


array([[ 2, 10,  1, 15],
       [ 1,  7,  2, 13],
       [ 4, 13,  7,  1],
       [ 4,  1,  9, 14]])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [136]:
arr=np.random.randint(0,3,(3,0))
print(arr)
print((~arr.any(axis=0).any()))
arr=np.random.randint(0,3,(3,10))
print(arr)
(~arr.any(axis=0).any())

[]
True
[[1 0 0 1 2 2 2 2 0 0]
 [1 1 1 2 0 0 2 0 0 2]
 [2 0 1 1 1 0 0 0 0 1]]


False

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [137]:
arr=np.random.randint(0,10,(1,8))
value=4
print(arr)
nearest=arr.flat[np.abs(arr-value).argmin()]
nearest

[[6 6 3 8 7 9 8 1]]


3

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [138]:
arr1=np.random.randint(0,10,(1,3))
arr2=np.random.randint(0,10,(3,1))
add=np.nditer([arr1,arr2,None])
for i,j,k in add:
  k[...]=i+j
add.operands

(array([[0, 8, 2]]), array([[3],
        [7],
        [7]]), array([[ 3, 11,  5],
        [ 7, 15,  9],
        [ 7, 15,  9]]))

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [139]:
class Array(np.ndarray):
  def __new__(cls,array,name="None"):
    obj=np.asarray(array).view(cls)
    obj.name=name
    return obj
  def __Array2__(self,obj):
    if obj is None:
      return self.info == getattr(obj,'name',"no name")

arr=Array(np.arange(10),"new_one")
arr.name

'new_one'

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [140]:
arr=np.ones(10,dtype=int)
print(arr)
arr2=np.random.randint(0,len(arr),10)
print(arr2)
np.add.at(arr,arr2,1)
print(arr)

print("or")

arr+=np.bincount(arr2,minlength=10)
print(arr)

[1 1 1 1 1 1 1 1 1 1]
[2 8 1 4 6 0 2 0 5 1]
[3 3 3 1 2 2 2 1 2 1]
or
[5 5 5 1 3 3 3 1 3 1]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [141]:
arr=[1,2,3,4,5,6,8,9]
arr2=[2,3,3,4,6,6,9,1]
F=np.bincount(arr2,arr)
F

array([ 0.,  9.,  1.,  5.,  4.,  0., 11.,  0.,  0.,  8.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [142]:
w,h=16,16
arr=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
A=arr[0]*(256*256) +arr[1]*256+arr[2]
len(np.unique(A))


8

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [143]:
arr=np.random.randint(0,10,(3,4))
add=arr.sum(axis=(-2,-1))
add

65

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [144]:
D=np.random.randint(0,100,100)
S=np.random.randint(0,10,100)
D_sum=np.bincount(S,D)
D_count=np.bincount(S)
D_mean=D_sum/D_count
print(D_mean)

[41.11111111 42.         40.71428571 53.6        65.66666667 45.3
 53.11111111 62.28571429 72.         54.05555556]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [145]:
arr1=np.random.randint(0,10,(5,5))
arr2=np.random.randint(0,10,(5,5))
np.diag(np.dot(arr1,arr2))

array([53, 86, 68, 52, 27])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [146]:
arr=np.array([1,2,3,4,5])
arr0=np.zeros(len(arr)+(len(arr)-1)*3)
arr0[::4]=arr
arr0

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [147]:
arr=np.ones((5,5,3))
arr2=5*np.ones((5,5))
arr*arr2[:,:,None]

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]]])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [148]:
arr=np.random.randint(0,100,(5,5))
print(arr)
arr[[2,4]]=arr[[4,2]]
print(arr)

[[26 97 77 94 40]
 [41 15 70 11 75]
 [34 42 23 76 52]
 [21 76 91 13 72]
 [56 90 54 22 56]]
[[26 97 77 94 40]
 [41 15 70 11 75]
 [56 90 54 22 56]
 [21 76 91 13 72]
 [34 42 23 76 52]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [149]:
triangle=np.random.randint(0,100,(10,3))
A=triangle.repeat(2,axis=1)
B=np.roll(A,-1,axis=1)
B=B.reshape(len(B)*3,2)
B=np.sort(B,axis=1)
C=B.view(dtype=[('p0',B.dtype),('p1',B.dtype)])
C=np.unique(C)
C

array([( 6, 61), ( 6, 86), (12, 39), (12, 53), (18, 52), (18, 65),
       (23, 24), (23, 81), (24, 81), (27, 51), (27, 85), (39, 53),
       (39, 84), (46, 51), (46, 85), (47, 59), (47, 66), (51, 85),
       (52, 65), (59, 66), (60, 77), (60, 83), (60, 90), (60, 92),
       (61, 86), (77, 92), (83, 90), (84, 84)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [153]:
C = np.bincount([1,1,2,3,4,5,6,6])
A=np.repeat(np.arange(len(C)),C)
A

array([1, 1, 2, 3, 4, 5, 6, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [154]:
arr=np.arange(10)
new=np.cumsum(arr,dtype=int)
n=3
new[n:]=new[n:]-new[:-n]
print(new)
print(new[n - 1:]/n)

[ 0  1  3  6  9 12 15 18 21 24]
[1. 2. 3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [155]:
from numpy.lib import stride_tricks

def rolling(a,n):
    n=4
    shape = (a.size - n + 1, n)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), n)
print(Z)


[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [156]:
arr=np.random.randint(0,3,10)
print(np.logical_not(arr,out=arr))
arr2=np.random.uniform(-1,1,10)
print(np.negative(arr2, out=arr2))


[1 0 0 0 0 1 0 0 1 0]
[ 0.08644906  0.93038096  0.78111161  0.51627394 -0.78167367  0.37252117
  0.46978034  0.76674303 -0.10147193  0.32218934]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [157]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(0,10,(10,2))
P1 = np.random.uniform(0,10,(10,2))
p  = np.random.uniform(0,10,( 1,2))
print(distance(P0, P1, p))

[2.84926286 3.93966035 7.71372144 7.75883918 0.67084546 6.5125979
 1.48576522 0.83776869 3.95665326 1.80504429]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [158]:
P0 = np.random.uniform(0, 10, (10,2))
P1 = np.random.uniform(0,10,(10,2))
p = np.random.uniform(0, 10, (10,2))
for p_i in p:
  print(np.array([distance(P0,P1,p_i)]))

[[3.26946119 5.07460653 4.18992536 2.37420678 5.50222667 0.48883836
  1.74062204 2.79571819 1.17813258 1.61841902]]
[[0.12986018 2.06472348 0.57998678 0.51827675 1.80196693 3.41609947
  2.07739567 0.46617952 3.06828204 2.28457432]]
[[0.90018954 2.74054554 1.83968176 2.42818978 3.17686547 1.56816613
  0.02576976 2.50939355 3.20114112 0.40189268]]
[[3.65803028 0.779983   3.36282394 3.00107428 2.33842781 8.25483621
  7.09786282 3.53266139 4.19590128 7.16306931]]
[[0.9864018  3.4263638  1.50338562 1.00156219 2.61623468 3.18407652
  2.23739446 0.88200346 1.3326492  2.10902785]]
[[2.1606739  0.2098258  1.24223099 2.12711551 0.10292792 4.40851631
  2.5539771  1.77148526 5.62049863 3.2045636 ]]
[[1.53642638 0.88265563 0.9582043  0.61109083 0.20284468 5.21015149
  3.89717872 0.85641869 3.66113446 4.08729965]]
[[0.32833396 0.96763708 1.01599342 5.66580022 2.57528784 1.05162368
  1.18935943 5.54622748 5.93075951 0.21784427]]
[[3.62607719 1.79545658 2.59617917 2.9705803  1.18282822 5.2812103
  3.1

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [159]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 3 1 6 4 6 1 5 7 3]
 [0 3 9 2 8 3 5 3 3 2]
 [6 3 4 6 5 3 1 4 7 0]
 [7 6 6 1 4 2 2 7 9 3]
 [9 8 7 1 0 3 3 6 9 6]
 [6 1 9 9 6 9 7 0 3 7]
 [6 9 6 5 4 1 6 3 4 3]
 [0 5 7 5 5 0 4 4 1 8]
 [1 7 4 1 8 0 3 7 9 2]
 [7 1 7 3 3 6 0 7 6 6]]
[[0 0 0 0 0]
 [0 5 3 1 6]
 [0 0 3 9 2]
 [0 6 3 4 6]
 [0 7 6 6 1]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [160]:
arr=np.arange(1,15,dtype=np.uint32)
R=stride_tricks.as_strided(arr,(11,4),(4,4))
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [161]:
arr=np.random.uniform(0,1,(5,6))
U, S, V = np.linalg.svd(arr)
rank = np.sum(S > 1e-10)
print(rank)

5


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [162]:
arr=np.random.randint(0,5,50)
np.bincount(arr).argmax()

0

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [163]:
arr = np.random.randint(0,4,(10,10))
n = 3
i = 1 + (arr.shape[0]-3)
j = 1 + (arr.shape[1]-3)
C = stride_tricks.as_strided(arr, shape=(i, j,n, n), strides=arr.strides+arr.strides )
print(C)


[[[[2 3 2]
   [1 3 0]
   [3 0 0]]

  [[3 2 0]
   [3 0 3]
   [0 0 0]]

  [[2 0 3]
   [0 3 3]
   [0 0 3]]

  [[0 3 1]
   [3 3 2]
   [0 3 1]]

  [[3 1 0]
   [3 2 0]
   [3 1 2]]

  [[1 0 2]
   [2 0 3]
   [1 2 3]]

  [[0 2 2]
   [0 3 1]
   [2 3 0]]

  [[2 2 3]
   [3 1 1]
   [3 0 3]]]


 [[[1 3 0]
   [3 0 0]
   [3 3 2]]

  [[3 0 3]
   [0 0 0]
   [3 2 1]]

  [[0 3 3]
   [0 0 3]
   [2 1 0]]

  [[3 3 2]
   [0 3 1]
   [1 0 1]]

  [[3 2 0]
   [3 1 2]
   [0 1 1]]

  [[2 0 3]
   [1 2 3]
   [1 1 0]]

  [[0 3 1]
   [2 3 0]
   [1 0 3]]

  [[3 1 1]
   [3 0 3]
   [0 3 0]]]


 [[[3 0 0]
   [3 3 2]
   [2 2 0]]

  [[0 0 0]
   [3 2 1]
   [2 0 0]]

  [[0 0 3]
   [2 1 0]
   [0 0 2]]

  [[0 3 1]
   [1 0 1]
   [0 2 1]]

  [[3 1 2]
   [0 1 1]
   [2 1 0]]

  [[1 2 3]
   [1 1 0]
   [1 0 2]]

  [[2 3 0]
   [1 0 3]
   [0 2 0]]

  [[3 0 3]
   [0 3 0]
   [2 0 1]]]


 [[[3 3 2]
   [2 2 0]
   [0 2 1]]

  [[3 2 1]
   [2 0 0]
   [2 1 3]]

  [[2 1 0]
   [0 0 2]
   [1 3 3]]

  [[1 0 1]
   [0 2 1]
   [3 3 1]]

  [[0 1 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [3]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5  9 13  2 12]
 [ 9  2 12  5  9]
 [13 12  7 42  4]
 [ 2  5 42  8  8]
 [12  9  4  8  1]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [164]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [165]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [166]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [8]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 3
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9997 9998 9999]
[9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [9]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [2]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [52]:
Z = np.random.randint(5e5)
A=(np.power(Z,3))
B=(Z*Z*Z)
#C=np.einsum('i,i,i->i', Z, Z,Z)
print(A)
print(B)
#print(C)

12315028600055089
12315028600055089


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [31]:
A = np.random.randint(0,4,(8,3))
B = np.random.randint(0,4,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((2,1)).all(1))[0]
print(A,B,C)
print(rows)

[[1 3 2]
 [3 3 2]
 [1 0 1]
 [2 0 0]
 [2 3 2]
 [2 2 0]
 [3 0 0]
 [2 1 2]] [[1 1]
 [3 2]] [[[[ True  True]
   [False False]]

  [[False False]
   [ True False]]

  [[False False]
   [False  True]]]


 [[[False False]
   [ True False]]

  [[False False]
   [ True False]]

  [[False False]
   [False  True]]]


 [[[ True  True]
   [False False]]

  [[False False]
   [False False]]

  [[ True  True]
   [False False]]]


 [[[False False]
   [False  True]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False  True]]

  [[False False]
   [ True False]]

  [[False False]
   [False  True]]]


 [[[False False]
   [False  True]]

  [[False False]
   [False  True]]

  [[False False]
   [False False]]]


 [[[False False]
   [ True False]]

  [[False False]
   [False False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False  True]]

  [[ True  True]
   [False False]]

  [[False False]
   [False  True]]]]
[0 1 2 4 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [37]:
Z = np.random.randint(0,2,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[0 1 1]
 [1 0 1]
 [0 0 0]
 [1 1 0]
 [0 1 1]
 [1 1 0]
 [0 0 0]
 [1 0 1]
 [1 1 1]
 [0 1 1]]
[[0 1 1]
 [1 0 1]
 [1 1 0]
 [0 1 1]
 [1 1 0]
 [1 0 1]
 [0 1 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [42]:
I = np.array([10, 28, 2, 3, 56, 106, 32, 111, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 1 0 1 0]
 [0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 1 1 1 0 0 0]
 [0 1 1 0 1 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 1 1 0 1 1 1 1]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [43]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]
[[0 0 0]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [55]:
A = np.random.uniform(0,1,5)
B = np.random.uniform(0,1,5)

print(np.einsum('i->', A))       # np.sum(A)
print(np.einsum('i,i->i', A, B)) # A * B
print(np.einsum('i,i', A, B))   # np.inner(A, B)
print(np.einsum('i,j->ij', A, B))    # np.outer(A, B)

3.15783284071477
[0.56589363 0.57368496 0.1073331  0.05581098 0.36811259]
1.670835249744112
[[0.56589363 0.56485338 0.08415891 0.52991619 0.51131238]
 [0.57474147 0.57368496 0.08547475 0.53820152 0.51930683]
 [0.72171939 0.7203927  0.1073331  0.67583513 0.65210852]
 [0.05960014 0.05949058 0.00886365 0.05581098 0.05385162]
 [0.40740763 0.40665873 0.06058909 0.38150616 0.36811259]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [58]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 100) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)
print(r_int,x_int,y_int)

[  0.           5.00090735  10.00181469  15.00272204  20.00362938
  25.00453673  30.00544407  35.00635142  40.00725876  45.00816611
  50.00907345  55.0099808   60.01088814  65.01179549  70.01270283
  75.01361018  80.01451752  85.01542487  90.01633222  95.01723956
 100.01814691 105.01905425 110.0199616  115.02086894 120.02177629
 125.02268363 130.02359098 135.02449832 140.02540567 145.02631301
 150.02722036 155.0281277  160.02903505 165.0299424  170.03084974
 175.03175709 180.03266443 185.03357178 190.03447912 195.03538647
 200.03629381 205.03720116 210.0381085  215.03901585 220.03992319
 225.04083054 230.04173788 235.04264523 240.04355257 245.04445992
 250.04536727 255.04627461 260.04718196 265.0480893  270.04899665
 275.04990399 280.05081134 285.05171868 290.05262603 295.05353337
 300.05444072 305.05534806 310.05625541 315.05716275 320.0580701
 325.05897745 330.05988479 335.06079214 340.06169948 345.06260683
 350.06351417 355.06442152 360.06532886 365.06623621 370.06714355
 375.068050

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [64]:
X = np.asarray([[2.0, 1.0, 6.0, 9.5],
                [3.0, 7.0, 1.0, 7.0],
                [1.5, 2.5, 0.0, 1.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [67]:
X = np.random.randn(100)
N = 1000
ind = np.random.randint(0, X.size, (N, X.size))
means = X[ind].mean(axis=1)
con = np.percentile(means, [5, 95])
print(con)

[-0.15166416  0.17609352]
